language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install pytest-cov
script:
- py.test
deploy:
  provider: pypi
  user: daveshawley
  password:
    secure: IWRFL0RNYUNTSvYnUgrBNTlaPKjMwEN5WlUKMwGQKNVsI4Cwj13Malk0v2XFOaS5ateKx1zHzb6c1I91TXHeYfRQAUURtm2GSGM1Rh/fClXudEJwp5mKEidOmZq0hr7XCtoU7sAPKUGhkE4onwys8TZtq45FmrYHoUPKATZswvw=
  distributions: sdist bdist_wheel
  on:
    all_branches: true
    tags: true
